FROM python:3

# See https://github.com/waveform80/picamera/issues/578
ENV READTHEDOCS=True

RUN mkdir -p /app
WORKDIR /app
ADD *.txt /app/ 
RUN pip3 install --break-system-packages -r requirements.txt
ADD *.py /app/



