version: "3"

networks:
    skyscan:
      driver: bridge
      driver_opts:
        com.docker.network.driver.mtu: 900

services:

  mqtt:
    networks:
      - skyscan
    image: iqtlabs/edgetech-mqtt-dev:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"

  object-ledger:
    networks:
      - skyscan
    image: iqtlabs/edgetech-object-ledger:v1.2
    restart: unless-stopped
    depends_on: 
      - mqtt
    env_file:
      - .env
      - object-ledger.env

  controller:
    networks:
      - skyscan
    image: iqtlabs/edgetech-axis-ptz-controller:v2.0
    volumes:
      - ./data/to_sort:/data/to_sort
    restart: unless-stopped
    depends_on:
      - mqtt
    env_file:
      - .env
      - axis-ptz-controller.env

  piaware:
    networks:
      - skyscan
    image: mikenye/piaware:latest
    tty: true
    container_name: piaware
    devices:
      - /dev/bus/usb:/dev/bus/usb
    ports:
      - 8080:80
      - 30003:30003
      - 30005:30005
    restart: unless-stopped
    env_file:
      - .env
      - piaware.env

  dump1090-json:
    networks:
      - skyscan
    image: iqtlabs/edgetech-dump1090-json:v1.1
    restart: unless-stopped
    depends_on: 
      - mqtt
      - piaware
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
    env_file:
      - .env
      - ./dump1090-json.env

  skyscan-c2:
    networks:
      - skyscan
    image: iqtlabs/edgetech-skyscan-c2:v1.0
    volumes:
      - ./data/mapping:/data/mapping
    restart: unless-stopped
    depends_on:
      - mqtt
      - object-ledger
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
    env_file:
      - .env
      - skyscan-c2.env

  # occlusion-mapper:
  #   networks:
  #     - skyscan
  #   image: iqtlabs/edgetech-occlusion-mapper:v1.0
  #   volumes:
  #     - ./data/mapping:/data/mapping
  #   ports:
  #     - "5000:5000"
  #   restart: unless-stopped
  #   depends_on:
  #     - mqtt
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10M"
  #       max-file: "10"
  #   env_file:
  #     - .env