version: "3"
services:
  watchtower:
    image: containrrr/watchtower:1.5.3
    network_mode: "host"
    environment:
      - WATCHTOWER_POLL_INTERVAL:3600
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval ${WATCHTOWER_POLL_INTERVAL:-3600}
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"

  ca:
    image: iqtlabs/edgetech-ca:${SERVICES_VERSION:-latest}
    env_file:
      - ${MQTT_PREFIX-.}/ca.env 
    hostname: ca
    volumes:
      - "${MQTT_PREFIX-.}/step:/home/step"
    networks:
      mqtt:
          aliases:
            - ca.mqtt.local
    expose:
      - 8051
      - 8050
    secrets:
      - ca_pass

  mqtt:
    image: iqtlabs/edgetech-mqtt:${SERVICES_VERSION:-latest}
    hostname: broker
    depends_on:
      ca:
        condition: service_healthy
    expose:
      - 8883
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"
    networks:
      mqtt:
        aliases:
          - broker.mqtt.local
    secrets:
      - mqtt_pass
      - mqtt_user

networks:
  mqtt:
    name: mqtt.local

secrets:
  ca_pass:
    file: ${MQTT_PREFIX-.}/.ca_password
  mqtt_pass:
    file: ${MQTT_PREFIX-.}/.mqtt_password
  mqtt_user:
    file: ${MQTT_PREFIX-.}/.mqtt_user

  