version: "3"
services:
  mqtt:
    image: iqtlabs/edgetech-mqtt:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    build:
      context: ../mqtt
      dockerfile: Dockerfile
    restart: unless-stopped
  filesaver:
    image: iqtlabs/auto-cal:latest
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - CONFIG_TOPIC="skyscan/config/json"
      - CALIBRATION_TOPIC="skyscan/calibration/json"
      - MQTT_IP="127.0.0.1"
      - EDGETECH_CORE_HOME=~/
    restart: unless-stopped
    depends_on:
      - mqtt