#FROM eclipse-mosquitto 
#LABEL maintainer = "Arizbeth Rojas <arojas@iqt.org>"
#RUN apk add --update curl mosquitto && rm -rf /var/cache/apk/*
#COPY mosquitto.conf /etc/mosquitto/nmosquitto.conf
#EXPOSE 1883
#ENTRYPOINT ["/usr/sbin/mosquitto", "-v", "-c", "/etc/mosquitto/mosquitto.conf"]
#ENTRYPOINT ["/bin/sh"]

FROM eclipse-mosquitto
LABEL maintainer = "Arizbeth Rojas <arojas@iqt.org>"
RUN apk update && apk add --no-cache certbot curl 
RUN apk add --update curl mosquitto && rm -rf /var/cache/apk/*
COPY mosquitto.conf /etc/mosquitto/nmosquitto.conf
#COPY certbot_renew.sh /certbot_renew.sh
#RUN chmod +x /certbot_renew.sh
EXPOSE 8883 443
#ENTRYPOINT ["/bin/sh", "$(cat /login_info_MQTT)"]
#ENTRYPOINT ["/bin/sh"]
COPY mqtt.sh .
RUN chmod +x /mqtt.sh
ENTRYPOINT ["./mqtt.sh"]

