FROM python:3

RUN mkdir -p /app/mqtt_wrapper/
WORKDIR /app/
ADD *.txt /app/ 
RUN pip3 install -r requirements.txt
ADD *.py /app/
ADD mqtt_wrapper /app/mqtt_wrapper/
#CMD ./adsb-mqtt.py -H 192.168.1.218 -m 192.168.1.218  -t skyscan/planes/json

