FROM python:3

RUN mkdir -p /app/mqtt_wrapper/
WORKDIR /app
ADD *.txt /app/ 
ADD static /app/static/
ADD templates /app/templates/
RUN pip3 install -r requirements.txt
ADD *.py /app/
ADD mqtt_wrapper /app/mqtt_wrapper/
#CMD ./flighttracker.py -H 192.168.1.218 -m broker.hivemq.com  -t skyscan

