# Prior to building, copy the following resources from
# IQTLabs/edgetech-core to the build directory:
#   - core/base_mqtt_pub_sub.py
#   - mqtt/*
version: "3"
services:
  mqtt:
    image: iqtlabs/edgetech-mqtt:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    build:
      context: ./mqtt
      dockerfile: ./Dockerfile
    restart: unless-stopped
  controller:
    image: iqtlabs/skyscan-ptz-controller:latest
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - MQTT_IP=mqtt
      - CAMERA_IP=${CAMERA_IP}
      - CAMERA_USER=${CAMERA_USER}
      - CAMERA_PASSWORD=${CAMERA_PASSWORD}
      - CONFIG_TOPIC=${CONFIG_TOPIC}
      - CALIBRATION_TOPIC=${CALIBRATION_TOPIC}
      - FLIGHT_TOPIC=${FLIGHT_TOPIC}
      - LOGGER_TOPIC=${LOGGER_TOPIC}
      - HEARTBEAT_INTERVAL=${HEARTBEAT_INTERVAL}
      - TRIPOD_LONGITUDE=${TRIPOD_LONGITUDE}
      - TRIPOD_LATITUDE=${TRIPOD_LATITUDE}
      - TRIPOD_ALTITUDE=${TRIPOD_ALTITUDE}
      - UPDATE_INTERVAL=${UPDATE_INTERVAL}
      - CAPTURE_INTERVAL=${CAPTURE_INTERVAL}
      - LEAD_TIME=${LEAD_TIME}
      - PAN_GAIN=${PAN_GAIN}
      - PAN_RATE_MIN=${PAN_RATE_MIN}
      - PAN_RATE_MAX=${PAN_RATE_MAX}
      - TILT_GAIN=${TILT_GAIN}
      - TILT_RATE_MIN=${TILT_RATE_MIN}
      - TILT_RATE_MAX=${TILT_RATE_MAX}
      - JPEG_RESOLUTION=${JPEG_RESOLUTION}
      - JPEG_COMPRESSION=${JPEG_COMPRESSION}
      - USE_MQTT=True
      - USE_CAMERA=False
      - LOG_TO_MQTT=True
    restart: unless-stopped
    depends_on:
      - mqtt
