version: "3"
services:
  mqtt:
    image: iqtlabs/edgetech-mqtt:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    build:
      context: ${MQTT_CONTEXT}
      dockerfile: ./Dockerfile
    restart: unless-stopped
  loop:
    image: iqtlabs/skyscan-ptz-controller:latest
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - CORE_PATH="/root"
      - CONFIG_TOPIC="skyscan/config/json"
      - CALIBRATION_TOPIC="skyscan/calibration/json"
      - FLIGHT_TOPIC="skyscan/flight/json"
      - LEAD_TIME=0.25
      - UPDATE_INTERVAL=0.10
      - GAIN_PAN=0.2
      - GAIN_TILT=0.2
      - MQTT_IP=mqtt
    restart: unless-stopped
    depends_on:
      - mqtt
