version: "3"
services:
  mqtt:
    image: iqtlabs/edgetech-mqtt:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    build:
      context: ./mqtt
      dockerfile: ./Dockerfile
    restart: unless-stopped
  filesaver:
    image: iqtlabs/edgetech-template:latest
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - CONFIG_TOPIC="skyscan/config/json"
      - CALIBRATION_TOPIC="skyscan/calibration/json"
      - FLIGHT_TOPIC="skyscan/flight/json"
      - LEAD_TIME="0.25"
      - UPDATE_INTERVAL="0.10"
      - GAIN_PAN="0.2"
      - GAIN_TILT="0.2"
      - MQTT_IP="127.0.0.1"
    restart: unless-stopped
    depends_on:
      - mqtt
