name: Container Processing

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get tag
      id: get_tag
      run: |
        echo "::set-output name=IMAGE_TAG::$(echo $GITHUB_REF | cut -d / -f 3)"
    
    - name: Set up qemu
      uses: docker/setup-qemu-action@v2
      with:
        platforms: all

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: latest

    - name: Docker Login
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Get Changes
      id: identify
      uses: jitterbit/get-changed-files@v1
    - run: |
        echo ${{ steps.files.output.all }}
    - name: Build Images
      env: 
        # Every folder in the repo that has a Dockerfile within it, comma separated 
        DOCKERFOLDERS: "edge-detect/ai,tracker,piaware,pan-tilt-pi,notebook-server,egi,axis-ptz"
        PROJECT_NAME: "skyscan"
      run: |
        IFS=","
        read -ra ARR <<< "$DOCKERFOLDERS"
        for folder in "${ARR[@]}"
        do 
          IFS="/"
          read -ra NAMEFOLDER <<< $folder
          SUBNAME=${NAMEFOLDER[0]}
          echo "Building $folder"
          echo $SUBNAME
          docker buildx build "$folder" --push \
          --tag iqtlabs/$PROJECT_NAME-$SUBNAME:latest \
          --tag iqtlabs/$PROJECT_NAME-$SUBNAME:${{ steps.get_tag.outputs.IMAGE_TAG }} \
          --platform linux/arm64,linux/amd64 
        done
