version: "3"
services:
  mqtt:
    image: iqtlabs/edgetech-mqtt:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    build:
      context: ${MQTT_CONTEXT}
      dockerfile: Dockerfile
    restart: unless-stopped
  filesaver:
    image: iqtlabs/skyscan-auto-calibrator:latest
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - CONFIG_TOPIC="skyscan/config/json"
      - CALIBRATION_TOPIC="skyscan/calibration/json"
      - MQTT_IP=mqtt
      - CORE_PATH="~/"
    restart: unless-stopped
    depends_on:
      - mqtt
